# Site settings
title: "Yves Theory"
description: "A peak into Yves's thoughts and projects."
baseurl: ""
url: "https://yvesdusenge.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/yvesdusenge
  - title: "git"
    url: http://github.com/yvesdusenge
  - title: "rss"
    url: /feed.xml
